
const TemplateNodes = {
  'VARIABLES': 'VARIABLES',
  'STYLE': 'STYLE',
  'QUESTION_MODEL': 'QUESTION MODEL',
  'PROCESS_MODE': 'PROCESS MODE',
  'SCOPING_ANALYSIS': 'SCOPING ANALYSIS',
  'PROBLEM_ARTICULATION_MODE': 'PROBLEM ARTICULATION',
  'CONSEQUENCE_MAPPING_MODE': 'CONSEQUENCE MAPPING'
}

module.exports = TemplateNodes
