
const TemplateNodes = {
  'VARIABLES': 'VARIABLES',
  'STYLE': 'STYLE',
  'QUESTION_MODEL': 'QUESTION MODEL',
  'PROCESS_MODE': 'PROCESS MODE',
  'SCOPING_ANALYSIS': 'SCOPING ANALYSIS',
  'PROBLEM_DEEPEN_MODE': 'PROBLEM DEEPEN',
  'RELEVANCE_MAPPING_MODE': 'RELEVANCE MAPPING',
  'SOLUTION_MAPPING_MODE': 'SOLUTION MAPPING'
}

module.exports = TemplateNodes
