
const TemplateNodes = {
  'PROBLEM_SPACE': 'PROBLEM SPACE',
  'PROBLEM_ANALYSIS': 'PROBLEM ANALYSIS',
  'PERCEIVED_PROBLEM': 'PERCEIVED PROBLEM',
  // 'STYLE': 'STYLE',
  'CONTEXT': 'CONTEXT',
  'GOODNESS_CRITERIA': 'GOODNESS CRITERIA'
}

module.exports = TemplateNodes
